# Generated by Django 5.2.1 on 2025-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_type_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeproduct',
            name='name',
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='nom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
