# Generated by Django 5.2.1 on 2025-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_typeproduct_name_typeproduct_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='product/gallery/'),
        ),
    ]
