# Generated by Django 5.2.1 on 2025-06-08 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pointconversion_popupadvertisement_advertisement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviseCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(max_length=10)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devise_info', to='core.country')),
            ],
        ),
    ]
