# Generated by Django 5.2.1 on 2025-06-08 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_devisecountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroPaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='numeropaye/')),
                ('numero_paye', models.CharField(max_length=30)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numero_paye', to='core.country')),
            ],
        ),
    ]
