# Generated by Django 5.2.1 on 2025-06-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
