# Generated by Django 5.2.1 on 2025-06-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lottery_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_participants', models.PositiveIntegerField(help_text='Nombre maximum de participants')),
                ('is_active', models.BooleanField(default=True)),
                ('number_of_winners', models.PositiveIntegerField(default=1)),
                ('participation_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Frais de participation en monnaie locale', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_transaction', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_winner', models.BooleanField(default=False)),
                ('winner_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.lottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
