# Generated by Django 5.2.1 on 2025-06-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_lottery_lotteryparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='target_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_lotteries', to='core.city'),
        ),
        migrations.AddField(
            model_name='lottery',
            name='target_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_lotteries', to='core.country'),
        ),
    ]
