# Generated by Django 5.2.1 on 2025-06-10 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productpoints_photopoints_contactproductpoints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='max_target_users',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_address_keywords',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_cities',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_communes',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_keywords',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_latitude',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_longitude',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='target_radius_km',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='targeted_users',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='core.store'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_targeted', to='core.city'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_targeted', to='core.country'),
        ),
    ]
