# Generated by Django 5.2.1 on 2025-06-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_advertisement_max_target_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupadvertisement',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popup_ads', to='core.store'),
        ),
        migrations.AddField(
            model_name='popupadvertisement',
            name='target_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popup_ads_targeted', to='core.city'),
        ),
        migrations.AddField(
            model_name='popupadvertisement',
            name='target_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popup_ads_targeted', to='core.country'),
        ),
    ]
