# Generated by Django 5.2.1 on 2025-06-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_advertisementpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
    ]
