# Generated by Django 5.2.1 on 2025-06-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='draw_done',
            field=models.BooleanField(default=False),
        ),
    ]
