# Generated by Django 5.2.1 on 2025-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_pointsharinggroup_pointstransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='max_comments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='max_interactions',
            field=models.PositiveIntegerField(blank=True, help_text='Max global : likes + shares + commentaires', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='max_likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
