# Generated by Django 5.2.1 on 2025-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_advertisement_max_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='max_interactions',
            field=models.PositiveIntegerField(blank=True, help_text='Non utilisé ici (remplacé par les 3 limites individuelles)', null=True),
        ),
    ]
