# Generated by Django 5.2.1 on 2025-07-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_advertisement_max_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='max_interactions',
            field=models.PositiveIntegerField(blank=True, help_text='Valeur identique appliquée à chaque type : likes, shares, comments', null=True),
        ),
    ]
