# Generated by Django 5.2.1 on 2025-07-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_advertisement_max_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='core.country'),
        ),
    ]
