# Generated by Django 5.2.1 on 2025-06-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('core', '0027_lottery_draw_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('commune', models.CharField(help_text='Entrez la commune manuellement', max_length=100)),
                ('description', models.TextField()),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('hotel', 'Hôtel'), ('guesthouse', 'Guesthouse'), ('boutique', 'Boutique'), ('parcelle vide', 'Parcelle vide'), ('terrain agricole', 'Terrain agricole'), ('bureau', 'Bureau'), ('autres', 'Autres')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/requests/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/responses/')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='base.requete')),
            ],
        ),
    ]
